name: mpabot_codeproject_parser

services:

  # CodeProject Parsing Service (9095)
  codeproject-parser-web:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/tmp/nginx.conf
    environment:
      - FLASK_SERVER_ADDR=codeproject-parser-backend:9095
    command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    ports:
      - 220:220
    depends_on:
      - codeproject-parser-backend
    networks:
      - subnet

  codeproject-parser-backend:
    container_name: codeproject-parser-backend
    image: codeproject_parsing_service_backend
    build:
      context: app
      target: builder
    stop_signal: SIGINT
    environment:
      - FLASK_SERVER_PORT=9095
      - MONGO_URI=mongodb://codeproject-parser-mongo:27017/codeproject-parser_db
    volumes:
      - ./app:/src
    depends_on:
      - codeproject-parser-mongo
    networks:
      - subnet
      - data-net

  # Reddit DB (50004)
  codeproject-parser-mongo:
    container_name: codeproject-parser-mongo
    image: mongo
    ports:
      - 50004:27017
    volumes:
      - codeproject-parser-data:/data/db
    networks:
      - subnet

networks:
  subnet:
    driver: bridge
  data-net:
    external:
      name: mpabot_data_controller_data-net


volumes:
  codeproject-parser-data: